import os
import time
import sys

def gameover( playermodel ):

    o = .1

    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |______ {playermodel}      |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |______{playermodel}       |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |_____{playermodel}        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |____{playermodel}_        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |___{playermodel}__        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |__{playermodel}___        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |_{playermodel}____        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print(f'|        |      |{playermodel}_____        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print('|        |      | |   |        |')
    print(f'|        |      |{playermodel}|___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print('|         ______   ______      |')
    print(f'|        |      |{playermodel}|   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         ______ {playermodel} ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         ______ {playermodel} ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear')

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         _____{playermodel}   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         ____{playermodel}_   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         ___{playermodel}__   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         __{playermodel}___   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         _{playermodel}____   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|         {playermodel}_____   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|        {playermodel}______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|       {playermodel} ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|      {playermodel}  ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|     {playermodel}   ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|    {playermodel}    ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    print(' \n' * 7 )
    print( 'Map:' )
    print(' --------              --------')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |            |        |')
    print('|        |____________|__      |')
    print(f'|   {playermodel}     ______   ______      |')
    print('|        |      | |   |        |')
    print('|        |      | |___|________|')
    print('|        |      |______        |')
    print('|        |             |   💎   |')
    print(' ---------              -------')
    print( f'You: {playermodel}' )
    print('')

    time.sleep(o)
    os.system( 'clear' )

    playermodel2 = "💎" + playermodel

    print( f'____________________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'{playermodel2}___________________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_{playermodel2}__________________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__{playermodel2}_________________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___{playermodel2}________________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'____{playermodel2}_______________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_____{playermodel2}______________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______{playermodel2}_____________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_______{playermodel2}____________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'________{playermodel2}___________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_________{playermodel2}__________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__________{playermodel2}_________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________{playermodel2}________________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'____________{playermodel2}_______________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_____________{playermodel2}______________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______________{playermodel2}_____________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_______________{playermodel2}____________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'________________{playermodel2}___________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_________________{playermodel2}__________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__________________{playermodel2}_________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________{playermodel2}________________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'____________________{playermodel2}_______________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_____________________{playermodel2}______________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______________________{playermodel2}_____________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_______________________{playermodel2}____________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'________________________{playermodel2}___________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_________________________{playermodel2}__________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__________________________{playermodel2}_________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )

    print( f'___________________________{playermodel2}_______________________________🌲' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_____________________________🌲__' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}__________________________🌲_____' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_______________________🌲________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}____________________🌲___________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_________________🌲______________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}______________🌲_________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}___________🌲____________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________🌲_______________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_____🌲__________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}__🌲_____________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'________________________🌲__{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_____________________🌲_____{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__________________🌲________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_______________🌲___________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'____________🌲______________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_________🌲_________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______🌲____________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___🌲_______________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'🌲__________________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_______________________________🏎' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_____________________________🏎__' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}__________________________🏎_____' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_______________________🏎________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}____________________🏎___________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_________________🏎______________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}______________🏎_________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}___________🏎____________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}________🏎_______________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}_____🏎__________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel2}__🏎_____________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______________________________🏎💎_____________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________🏎💎________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'________________________🏎💎__{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_____________________🏎💎_____{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'__________________🏎💎________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_______________🏎💎___________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'____________🏎💎______________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'_________🏎💎_________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'______🏎💎____________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___🏎💎_______________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'🏎💎__________________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'💎___________________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( f'___________________________{playermodel}________________________________' )
    time.sleep(o)
    os.system( 'clear' )
    print( 'Thanks for playing!' )

    sys.exit()